/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package docentes.vistas;

import docentes.modelos.Docente;
import docentes.modelos.ModeloTablaDocentes;
import javax.swing.event.ListSelectionEvent;
import javax.swing.event.ListSelectionListener;

/**
 *
 * @author root
 */
public class VentanaDocentes extends javax.swing.JDialog {

    /**
     * Creates new form VentanaDocentes
     */
    public VentanaDocentes(java.awt.Frame parent, ModeloTablaDocentes mtd) {
        super(parent, true);
        initComponents();
        this.tablaDocentes.setModel(mtd);
        
        this.tablaDocentes.getSelectionModel().addListSelectionListener(new ListSelectionListener() {
            @Override
            public void valueChanged(ListSelectionEvent e) {
                if (!e.getValueIsAdjusting()) {
                    //En esta tabla se puede seleccionar sólo un elemento a la vez, 
                    //por lo que cuando se realiza una nueva selección, 
                    //el elemento seleccionado anteriormente se convierte en no seleccionado, 
                    //disparándose 2 eventos cada vez que se selecciona un elemento diferente
                    //Para evitar responder al evento cuando un elemento deja de estar seleccionado
                    //y luego cuando otro queda seleccionado, se comprueba que esta secuencia de eventos
                    //esté terminada mediante getValueIsAdjusting()
                    int fila = tablaDocentes.getSelectedRow();
                    Docente unDocente = mtd.verDocente(fila);
                    unDocente.mostrar();
                }
            }
        });
        
        this.setLocationRelativeTo(null);
        this.setVisible(true);
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jScrollPane1 = new javax.swing.JScrollPane();
        tablaDocentes = new javax.swing.JTable();

        setDefaultCloseOperation(javax.swing.WindowConstants.DISPOSE_ON_CLOSE);
        setTitle("Docentes");
        setResizable(false);

        tablaDocentes.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null}
            },
            new String [] {
                "Title 1", "Title 2", "Title 3", "Title 4"
            }
        ));
        jScrollPane1.setViewportView(tablaDocentes);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jScrollPane1, javax.swing.GroupLayout.DEFAULT_SIZE, 388, Short.MAX_VALUE)
                .addContainerGap())
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 216, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(78, Short.MAX_VALUE))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    
    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JTable tablaDocentes;
    // End of variables declaration//GEN-END:variables
}
